services:
  crate:
    container_name: crate
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: unless-stopped
    ports:
      - "4010:4000"
    volumes:
      - /mnt/z1/docker/crate/data:/app/data
    environment:
      TZ: America/Chicago
      NODE_ENV: production
      PORT: 4000
