services:
  crate:
    container_name: crate
    build:
      context: /mnt/z1/docker/crate/app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4010:4000"
    volumes:
      - /mnt/z1/docker/crate/data:/app/data
    environment:
      NODE_ENV: production
      PORT: 4000
